# Generated by Django 3.1.2 on 2020-10-10 15:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', models.FileField(upload_to='images/', validators=[django.core.validators.FileExtensionValidator(['png', 'svg', 'jpg'])])),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование')),
                ('amount', models.IntegerField(verbose_name='Колличество')),
                ('vendor_code', models.CharField(max_length=50, verbose_name='Штрих код товара')),
            ],
        ),
    ]
